CREATE TABLE USERS
(
  USER_ID NUMBER(*, 0) DEFAULT 0 NULL
, FULL_NAME VARCHAR2(50 BYTE)
, BILLING_ADDRESS VARCHAR2(50 BYTE)
, LOGIN VARCHAR2(50 BYTE) NOT NULL
, PASSWORD VARCHAR2(50 BYTE) NOT NULL
, CONSTRAINT USERS_PK PRIMARY KEY
  (
    USER_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX USERS_PK ON USERS (USER_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOPARALLEL;

ALTER TABLE USERS
ADD CONSTRAINT USERS_UK1 UNIQUE
(
  LOGIN
)
USING INDEX
(
    CREATE UNIQUE INDEX USERS_UK1 ON USERS (LOGIN ASC)
    LOGGING
    TABLESPACE USERS
    PCTFREE 10
    INITRANS 2
    STORAGE
    (
      INITIAL 65536
      NEXT 1048576
      MINEXTENTS 1
      MAXEXTENTS UNLIMITED
      BUFFER_POOL DEFAULT
    )
    NOPARALLEL
)
 ENABLE;

CREATE TABLE ITEMS
(
  ITEM_ID NUMBER(*, 0) DEFAULT 0 NOT NULL
, SELLER_ID NUMBER(*, 0) NOT NULL
, TITLE VARCHAR2(50 BYTE) NOT NULL
, DESCRIPTION VARCHAR2(50 BYTE)
, START_PRICE NUMBER(*, 2) NOT NULL
, TIME_LEFT NUMBER(*, 0)
, START_BIDDING_DATE DATE NOT NULL
, BUY_IT_NOW NUMBER(*, 0) NOT NULL
, BID_INCREMENT NUMBER(*, 2)
, CONSTRAINT ITEMS_PK PRIMARY KEY
  (
    ITEM_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX ITEMS_PK ON ITEMS (ITEM_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOPARALLEL;



CREATE TABLE BIDS
(
  BID_ID NUMBER(*, 0) DEFAULT 0 NOT NULL
, BIDDER_ID NUMBER(*, 0) NOT NULL
, ITEM_ID NUMBER(*, 0) NOT NULL
, BID NUMBER(*, 2) NOT NULL
, CONSTRAINT BIDS_PK PRIMARY KEY
  (
    BID_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX BIDS_PK ON BIDS (BID_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOPARALLEL;